version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: reordena_abc
      POSTGRES_USER: gastro
      POSTGRES_PASSWORD: gastro123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: