"""fix abc_percentage precision

Revision ID: 156f41c5c9a0
Revises: a818638ad4cc
Create Date: 2026-05-02 21:32:51.466473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '156f41c5c9a0'
down_revision: Union[str, None] = 'a818638ad4cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'abc_percentage',
               existing_type=sa.NUMERIC(precision=6, scale=4),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'abc_percentage',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.NUMERIC(precision=6, scale=4),
               existing_nullable=True)
    # ### end Alembic commands ###
